name = "IndexedStructVectors"
uuid = "943997de-97ed-46fb-843d-45d8ceac30b4"
authors = ["Adriano Meligrana <adrianomeligrana@proton.me>"]
version = "0.1.0"

[deps]
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[compat]
Unrolled = "0.1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
