name = "IdTables"
uuid = "0cab796c-4e47-5d3e-808d-798fc581da82"
authors = ["Adriano Meligrana <adrianomeligrana@proton.me>", "Nathan Zimmerberg"]
version = "0.1.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[compat]
StructArrays = "0.7"
Tables = "1"
Unrolled = "0.1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
